name: Deploy automation

on:
  issues:
    types: opened

jobs:
  welcome:
    name: Welcome
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: echo "New Issue"

  setup:
    if: contains(github.event.issue.labels.*.name, 'deploy-automation')
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup Deploy
        run: echo "Deploy"
      - name: Save pipeline link on issue
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            You can track the action execution in [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Checkout do repositório
        uses: actions/checkout@v2
      - name: Exibir conteúdo da branch homolog
        run: |
          git fetch --all
          git checkout homolog
          cat .homolog